### ISSUE TITLE
Can't enable the extension?

### ISSUE THREAD

**Issue by MrDodojo** [NeverDecaf/discord-PWA#11]
I installed the extension but I can't enable it. Didn't see anyone having this issue yet, the chrome extensions page says this about the extension:' This extension is not listed in the Chrome Web Store and may have been added without your knowledge. '

**Comment by NeverDecaf** [comment]
Google has made it nigh-impossible to use extensions in Google Chrome that are not from the Chrome Web Store. See #6, #7, I will add a note to the readme.
