### ISSUE TITLE
PWA Keeps crashing

### ISSUE THREAD

**Issue by NoozAbooz** [NeverDecaf/discord-PWA#13]
When I open the PWA and go onto a server and send a message, this shows up: 
![image](https://user-images.githubusercontent.com/44128563/93544451-5abd2580-f91b-11ea-84df-ef6d9729dfc5.png). One of my friends also said the PWA has been crashing a lot for him too lately. I believe the error started occurring starting at  about 10:00 pm GMT today on the 17th.

**Comment by NeverDecaf** [comment]
Can't reproduce this, are you sure it isn't caused by a discord outage?

**Comment by NoozAbooz** [comment]
I don't think so. The problem has stopped occurring for the most part, but sometimes it still happens. Could be a problem with my internet or something to do with my pi.
