### ISSUE TITLE
Provide instructions to build the chrome extension

### ISSUE THREAD

**Issue by srevinsaju** [NeverDecaf/discord-PWA#14]
Great Project!

I am interested to know how the crx extension was built
I am not a fan of binaries in git repositories. I would like to see how you built it, to ensure security and transparency. 

Thanks :D

**Comment by NeverDecaf** [comment]
CRX is an archive file format similar (or perhaps identical) to ZIP with some extra metadata, presumably the extension's public key. You can extract the contents with a program like 7zip, but you may need to rename the file to `.zip` first depending on the method used. To create a CRX file visit `chrome://extensions`, enable developer mode, and click `Pack extension`.

**Comment by srevinsaju** [comment]
Cool. thanks for the information
