### ISSUE TITLE
Background notifications?

### ISSUE THREAD

**Issue by KibSquib48** [NeverDecaf/discord-PWA#16]
I've been using this PWA for a while and I love not having to worry about discord being slow or slowing down anything else. The one thing I do miss is background notifications, and I was wondering if it was possible to do it, since the Twitter PWA has background notifications too (notifications without the app/website running)

**Comment by NeverDecaf** [comment]
Unfortunately this isn't really feasible for me to add. All this PWA does is just open the website and pull a bit of data from it to enable notifications. Background notifications would mean recreating a large portion of the client using discord's API which, frankly, is a ton of work I'm not willing to do. Additionally, doing so would be a violation of their terms of service, qualifying as either a `self-bot` or `unofficial client` or both, which are things they *will* ban for. If you want more a more complete PWA I recommend you [petition Discord](https://support.discord.com/hc/en-us/community/posts/360031002972-Discord-as-a-PWA) to create an official PWA.
