### ISSUE TITLE
Issue with Using VPN Extensions

### ISSUE THREAD

**Issue by NonstickAtom785** [NeverDecaf/discord-PWA#27]
Using a Chrome VPN extension with the app causes some unknown login stuff, that doesn't show up anywhere else nor does it show for any other app either. I have used a couple of them and so far the same behavior for all. Discord PWA refuses to load. Yet the VPN is working just fine in the browser itself. Let me know if there is anything more I can do to help.

![DeepinScreenshot_select-area_20210515200703](https://user-images.githubusercontent.com/36454623/118375368-2177ab00-b5b9-11eb-9100-15bd6f804c2f.png)

**Comment by NeverDecaf** [comment]
Are there any errors (red text) displayed in the javascript console (`ctrl+shift+j`)?

I don't have any experience with VPN extensions so this is difficult to diagnose, I tried a [free VPN extension](https://chrome.google.com/webstore/detail/1clickvpn-free-vpn-for-ch/fcfhplploccackoneaefokcmbjfbkenj) from the web store and it worked fine for me. Do you have a link to one that doesn't work which I can try without making an account?

I found this: https://windscribe.com/support/article/6/usernamepassword-browser-popup with a quick search, can you try their suggested solution of pressing cancel? If that doesn't work, reinstalling the VPN extension (assuming you installed it before Discord PWA Helper) might also work.

edit: Another thing you might try is installing the CRX from the [manifestv3 branch](https://github.com/NeverDecaf/discord-PWA/tree/manifestv3). This uses a slightly different method to modify the CORS headers and might somehow resolve your issue.

**Comment by NonstickAtom785** [comment]
Okay so I use Hoxx VPN Proxy. You might find it odd that doing `ctrl+shift+j` doesn't open up the console. Which is wierd to me. I was going to check but it didn't work. I finally got it work by pressing cancel. But before today, still made it pop up again a few seconds later. So as to what happend I have no clue. Since I the console won't open normally I may actually try to open it another way. As for that Helper Extension this works too. It works without and with it. But the popup still comes on. Thanks for the advice.

Also I have an adequet knowledge in all of this stuff. No need to elaborate. (Just a heads up 😂). If I do figure out how to open the console I let you know. Until then I'm closing this issue until I see something else that I hadn't noticed before.

**EDIT:** Hm I just tried it again. And not pressing cancel still doesn't work. Same behavior as before.

**Comment by NeverDecaf** [comment]
Really strange, feels like one of those quirks of Chromium, similar to extension install order affecting which extension can modify headers (see #5). In other words, it might be something that has no fix besides the cancel thing. If you are only seeing a second popup and not multiple then it might have to do with the PWA loading an iframe, so having to press cancel twice might be normal.
As for opening the console, you can try `F12` but I have a feeling there won't actually be any error output from this.

**Comment by NonstickAtom785** [comment]
I finally figured it out. It was a configuration issue. I had done some pretty hacky things to my chromium, I went in and fixed it up though. So it's not normal behavior to say the least. I have it figured out now. I think I'm going to work on the interface a little bit now though. There are some things bugging me with header and some of the url event things. lol. Happy Programming!
