### ISSUE TITLE
Logs me out when I close it

### ISSUE THREAD

**Issue by ghost** [NeverDecaf/discord-PWA#35]
when I close it it logs me out every time, is there a way to stay signed in?
didnt found an issue about it

or is this an issue related to my browser?
- ungoogled chromium

**Comment by NeverDecaf** [comment]
Click the eye (Third-party cookie blocking) in the title bar then click `Site not working?` > `Allow cookies`
![image](https://user-images.githubusercontent.com/19150416/132954915-3ee6dc03-13aa-450f-8fa5-20b287ecbf9f.png)
If that isn't the problem, you may have an extension like uMatrix that's blocking or deleting cookies as well.

**Comment by ghost** [comment]
Yep it was the Scissor, thanks!
