### ISSUE TITLE
Update Discord logo

### ISSUE THREAD

**Issue by ghost** [NeverDecaf/discord-PWA#36]
It's your call: https://discord.com/branding

**Comment by ghost** [comment]
Maybe I have misunderstood, but that commit doesn't seem to affect the icons used. It still displays the old icon, and some images in this repo are also still the old version. Am I missing something?

**Comment by NeverDecaf** [comment]
As far as I can tell, PWA Icons are only set when the app is installed. To update to the new icon you have to completely remove the PWA and reinstall it.
