### ISSUE TITLE
Ungoogled-Chromium PWA issue after restart -  Cannot read properties of undefined (reading 'frameId')

### ISSUE THREAD

**Issue by klauss194** [NeverDecaf/discord-PWA#38]
Dear NeverDecaf,

I love the extension. I long dreamed of such setup to have discord running as a PWA therefore allowing my JS in page to be run. I have installed the extension and everything worked well. Until I had to restart computer. Suddenly the extension doesn't work and the link doesn't open anymore ( Popos - Ubuntu ). I have reinstalled the extension with no luck. I have openned the extension inspector to find out it is having this error:

`
Error handling response: TypeError: Cannot read properties of undefined (reading 'frameId')
    at chrome-extension://edfpalahildnikdjdnmmoekoncglnblh/background.js:90:82
`
Is there anyway we could further debug this ? 
Many thanks
K

**Comment by NeverDecaf** [comment]
Sorry for the late reply; have you tried removing the extension and reinstalling it? There is some behavior with extensions that depends on install order so there's a chance that will resolve it.

**Comment by NeverDecaf** [comment]
Sorry for the late reply; if you've already tried reinstalling the extension I can't think of much else that might easily fix this. It seems like maybe the way PWAs are handled in your setup is causing `webNavigation.getAllFrames` to fail. One other thing you can try is navigating to `chrome://apps/` in your browser and launching the PWA directly from there if you aren't already.

**Comment by NeverDecaf** [comment]
Feel free to re-open if you see this.
