### ISSUE TITLE
Dark Mode Title Bar

### ISSUE THREAD

**Issue by leafgrass95** [NeverDecaf/discord-PWA#42]
I am one of the weird few who use dark mode only when their eyes are actually burning, due to my difficulty reading white on black, which means most of the time discord is in light mode and my title bar is set in settings to match.

Is there anyway to implement a feature where it can change colour when dark mode is active?

**Comment by NeverDecaf** [comment]
Should be possible.

**Comment by NeverDecaf** [comment]
Make sure `Enable custom theme color` (extension options) is **NOT** checked. The titlebar color should change to match your current discord theme.
