### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by NoozAbooz** [NeverDecaf/discord-PWA#7]
When I tried to download the extension I got the error `package is invalid crx_required_proof_missing`. I found out this meant to distribute the extension from now on you have to put it on the chrome web store.

**Comment by NeverDecaf** [comment]
see #6

**Comment by ghost** [comment]
@NeverDecaf Do you intend to upload this extension to the Chrome Web Store? It eliminates this problem completely.

**Comment by NeverDecaf** [comment]
I do not currently have any plans to create a Google developer account, though I would not be opposed to someone else uploading this to the Chrome Web Store (whether Google would approve it is another matter).
