### ISSUE TITLE
Does not load correctly if browser is not open

### ISSUE THREAD

**Issue by NeverDecaf** [NeverDecaf/discord-PWA#8]
If you try to open the PWA directly from a shortcut while chrome(ium) is not running, the extension will not be loaded and therefore the PWA will fail to access discord.com. This causes the extension to be loaded, and refreshing the PWA (with ctrl+r) will then cause it to load correctly.

**Comment by ghost** [comment]
Came here to ask about this. Is this a Chromium bug, or is there a chance it's fixable on this project's end?

**Comment by NeverDecaf** [comment]
A workaround should be possible, but will most likely require some hack which may be messy, I will look into it.

**Comment by NeverDecaf** [comment]
Here is a quick description of the method I've used for future reference:
- Detect whether the extension is installed by attempting to access `chrome-extension://edfpalahildnikdjdnmmoekoncglnblh/manifest.json`. (manifest.json must be added to `web_accessible_resources` in manifest.)
- PWA can also use this manifest.json to get the currently installed extension version for update checking.
- Detect whether content script has been loaded by sending a message from the iframe using `parent.postMessage`. The PWA waits for this message and if it isn't received the iframe is reloaded (once only).
