### ISSUE TITLE
Menu bars are blank

### ISSUE THREAD

**Issue by NoozAbooz** [NeverDecaf/discord-PWA#9]
I went to the extension settings and tried changing the 'highlight icon when' option. Both menus showed up blank.![IMG_20200903_094638.jpg](https://user-images.githubusercontent.com/44128563/92137760-c99e6880-edca-11ea-9cb5-ddda84b4a5a2.jpg)![Screenshot_2020-09-03-09-46-18-870_com.realvnc.viewer.android.jpg](https://user-images.githubusercontent.com/44128563/92137770-cefbb300-edca-11ea-96c4-8f7ac0053e26.jpg)

**Comment by NeverDecaf** [comment]
The options page is just very basic HTML so I can't imagine how this is happening but it is very likely an issue with your browser and not the extension itself. 

If you just want to change these values you can inspect the background page and run some code in the console to adjust them manually. For example: `chrome.storage.sync.set({badge_count: "messages", draw_attention_on: "never"});`

**Comment by NoozAbooz** [comment]
Also what options are there for badge_count and draw_attention_on?

**Comment by NeverDecaf** [comment]
`mentions`,`channels`,`messages`,`never` are the 4 options available atm.
